

///////////////////////////////////////// HOW TO USE /////////////////////////////////////////

// 1. Go to MongoDB compass or similar tool and drop the "users" and "items" collections in the FixHub database 
// 2. Run the script using the command: node backend/config/mockBackendScript.js
// 3. Check the MongoDB compass or similar tool to see the new "users" and "items" collections, that contain the mock data.

// Take note that the userSchema is modified that the userId is automatically generated by MongoDB

///////////////////////////////////////////////////////////////////////////////////////////////



// Load environment variables
require('dotenv').config();

// Import Mongoose
const mongoose = require('mongoose');

// Define MongoDB URI
const DB_URI = process.env.DB_URI || 'mongodb://localhost:27017/FixHub';

// Define Mongoose Schemas
const userSchema = new mongoose.Schema(
    {
        name: {
            type: String,
            required: [true, 'Name is required'],
            trim: true,
            minlength: [3, 'Name must be at least 3 characters long'],
        },
        userName: {
            type: String,
            required: [true, 'Username is required'],
            unique: true,
            trim: true,
            minlength: [3, 'Username must be at least 3 characters long'],
        },
        password: {
            type: String,
            required: [true, 'Password is required'],
            minlength: [6, 'Password must be at least 6 characters long'],
        },
        phone: {
            type: String,
            required: [true, 'Phone number is required'],
            match: [/^\d{10,15}$/, 'Phone number must contain 10 to 15 digits'],
        },
        email: {
            type: String,
            required: [true, 'Email is required'],
            unique: true,
            lowercase: true,
        },
        location: {
            province: { type: String, required: true },
            city: { type: String, required: true },
            postalcode: { type: String, required: true, match: [/^\d{5}$/, 'Postal code must be 5 digits'] },
        },
        isFixer: {
            type: Boolean,
            default: false,
        },
        about: {
            type: String,
            default: '',
            maxlength: [500, 'About section must be less than 500 characters'],
        },
        profilePicture: {
            type: String,
            default: '', // URL to the profile picture
        },
        reviewCount: {
            type: Number,
            default: 0,
            min: [0, 'Review count cannot be negative'],
        },
        rating: {
            type: Number,
            default: 0,
            min: [0, 'Rating cannot be negative'],
            max: [5, 'Rating cannot exceed 5'],
        },
    },
    { timestamps: true }
);

const itemSchema = new mongoose.Schema(
    {
        userId: { 
            type: mongoose.Schema.Types.ObjectId, 
            ref: 'users', 
            required: true,
        },
        fixerId: { 
            type: mongoose.Schema.Types.ObjectId, 
            ref: 'users',
        },
        name: { 
            type: String, 
            required: true, 
            trim: true,
        },
        tags: { 
            type: [String], 
            default: [],
        },
        description: { 
            type: String, 
            required: true, 
            trim: true,
        },
        category: { 
            type: String, 
            required: true, 
            enum: ["Category1", "Category2", "Category3", "Category4", "Category5"],
        },
        location: {
            province: { type: String, required: true }, // Yksittäiset kentät ovat required
            city: { type: String, required: true },
            postalcode: { type: String, required: true, match: [/^\d{5}$/, 'Postal code must be 5 digits'] },
        },
        priceRange: { 
            type: [Number], 
            validate: {
                validator: function (v) {
                    return v.length === 2 && v[0] <= v[1];
                },
                message: 'Price range must contain exactly two values: [min, max]',
            },
        },
        dateOfPublish: { 
            type: Date, 
            default: Date.now,
        },
        images: { 
            type: [String], 
            default: [],
        },
        isFixed: { 
            type: Boolean, 
            required: true,
        },
        interested: { 
            type: Number, 
            default: 0,
        },
    },
    { timestamps: true }
);

const User = mongoose.model('users', userSchema);
const Item = mongoose.model('items', itemSchema);

// Mock Data Arrays for Users
const names = [
    "Mikko Kikko", "Maija Meikäläinen", "Pekka Puuseppä",
    "Hannu Hanhi", "Sergei Sorsa", "Jorma Jäätelö",
    "Kalle Kukko", "Jukka Jätkä", "Matti Meikäläinen", "Liisa Lumi"
];
const userNames = [
    "Miki", "MAME", "PekkaP", "HannuH", "SergeiS", "JormaJ",
    "KalleK", "JukkaJ", "MattiM", "LiisaL"
];
const passwords = [
    "salasana", "password", "123456", "qwerty", "password123",
    "password1234", "password12345", "password", "password", "password"
];
const phoneNumbers = [
    "0401234567", "0501234567", "0601234567", "0701234567",
    "0801234567", "0901234567", "0402234567", "0502234567",
    "0602234567", "0702234567"
];
const emails = [
    "mikko.kikko@gmail.com", "maija.meikälä@gmail.com", "pekka.puuseppä@gmail.com",
    "hannuha@gmail.com", "serge@gmail.com", "jorma@gmail.com",
    "kalle@gmail.com", "jukka@gmail.com", "matti@gmail.com", "lili@gmail.com"
];
const locations = Array(10).fill({
    province: "Uusimaa",
    city: "Helsinki",
    postalcode: "00790",
});

// Mock Data Arrays for Items
const itemNames = ["Item1", "Item2", "Item3", "Item4", "Item5"];
const itemDescriptions = ["Description1", "Description2", "Description3", "Description4", "Description5"];
const itemCategories = ["Category1", "Category2", "Category3", "Category4", "Category5"];
const itemLocations = [
    { province: "Uusimaa", city: "Helsinki", postalcode: "00100" },
    { province: "Varsinais-Suomi", city: "Turku", postalcode: "20100" },
    { province: "Pirkanmaa", city: "Tampere", postalcode: "33100" },
    { province: "Pohjois-Pohjanmaa", city: "Oulu", postalcode: "90100" },
    { province: "Keski-Suomi", city: "Jyväskylä", postalcode: "40100" }
];
const itemTags = [["tag1", "tag2"], ["tag3", "tag4"], ["tag5", "tag6"], ["tag7", "tag8"], ["tag9", "tag10"]];
const itemPrices = [[10, 20], [15, 25], [20, 30], [25, 35], [30, 40]];
const itemImages = [["image1.jpg"], ["image2.jpg"], ["image3.jpg"], ["image4.jpg"], ["image5.jpg"]];


// Add Mock Data Function
async function addMockData() {
    try { 
        // Yhdistetään MongoDB:hen
        await mongoose.connect(DB_URI);
        console.log('Connected to MongoDB');

        // Lisätään mock-käyttäjät
        const mockUsers = names.map((name, index) => ({
            name,
            userName: userNames[index],
            password: passwords[index],
            phone: phoneNumbers[index],
            email: emails[index],
            location: locations[index],
            isFixer: index % 2 === 0,
            about: "I am a fixer",
            reviewCount: Math.floor(Math.random() * 10),
        }));

        const insertedUsers = await User.insertMany(mockUsers);
        console.log('Mock users added successfully');

        // Adds mock items
        const mockItems = itemNames.map((name, index) => ({
            userId: insertedUsers[index % insertedUsers.length]._id, // connects to a user
            fixerId: insertedUsers.find((user) => user.isFixer)?._id || null, // connects to a fixer if exists
            name,
            tags: itemTags[index],
            description: itemDescriptions[index],
            category: itemCategories[index],
            location: itemLocations[index],
            priceRange: itemPrices[index],
            images: itemImages[index],
            isFixed: false,
            interested: Math.floor(Math.random() * 10),
        }));

        await Item.insertMany(mockItems);
        console.log('Mock items added successfully');
    } catch (error) {
        console.error('Error adding mock data:', error);
    } finally {
        await mongoose.disconnect();
        console.log('Disconnected from MongoDB');
    }
}

// Run the script
addMockData();
