
///////////////////////////////////////// HOW TO USE /////////////////////////////////////////

// 1. Go to MongoDB compass or similar tool and drop the users collection in the FixHub database 
// 2. Run the script using the command: node config/mockBackendScript.js
// 3. Check the MongoDB compass or similar tool to see the new users collection with mock data

// Take note that the userSchema is modified that the userId is automatically generated by MongoDB

///////////////////////////////////////////////////////////////////////////////////////////////


// Load environment variables
require('dotenv').config();

// Import Mongoose
const mongoose = require('mongoose');

// Define MongoDB URI
const DB_URI = process.env.DB_URI || 'mongodb://localhost:27017/FixHub';

// Define Mongoose Schema and Model
const userSchema = new mongoose.Schema({
    name: String,
    userName: String,
    password: String,
    phone: String,
    email: String,
    location: {
        province: String,
        city: String,
        postalcode: String,
    },
    isFixer: Boolean,
    about: String,
    reviewCount: Number, // Automatically generated userId
});

const User = mongoose.model('users', userSchema);

// Mock Data Arrays
const names = [
    "Mikko Kikko", "Maija Meikäläinen", "Pekka Puuseppä",
    "Hannu Hanhi", "Sergei Sorsa", "Jorma Jäätelö",
    "Kalle Kukko", "Jukka Jätkä", "Matti Meikäläinen", "Liisa Lumi"
];
const userNames = [
    "Miki", "MAME", "PekkaP", "HannuH", "SergeiS", "JormaJ",
    "KalleK", "JukkaJ", "MattiM", "LiisaL"
];
const passwords = [
    "salasana", "password", "123456", "qwerty", "password123",
    "password1234", "password12345", "password", "password", "password"
];
const phoneNumbers = [
    "0401234567", "0501234567", "0601234567", "0701234567",
    "0801234567", "0901234567", "0402234567", "0502234567",
    "0602234567", "0702234567"
];
const emails = [
    "mikko.kikko@gmail.com", "maija.meikälä@gmail.com", "pekka.puuseppä@gmail.com",
    "hannuha@gmail.com", "serge@gmail.com", "jorma@gmail.com",
    "kalle@gmail.com", "jukka@gmail.com", "matti@gmail.com", "lili@gmail.com"
];
const locations = Array(10).fill({
    province: "Uusimaa",
    city: "Helsinki",
    postalcode: "00790"
});

// Database Connection and Mock Data Insertion
async function addMockData() {
    try {
        // Connect to MongoDB
        await mongoose.connect(DB_URI);
        console.log('Connected to MongoDB');

        // Add Mock Data
        const mockData = names.map((name, index) => ({
            name,
            userName: userNames[index],
            password: passwords[index],
            phone: phoneNumbers[index],
            email: emails[index],
            location: locations[index],
            isFixer: index % 2 === 0,
            about: "I am a fixer",
            reviewCount: Math.floor(Math.random() * 10),
        }));

        await User.insertMany(mockData);
        console.log('Mock data added successfully');
    } catch (error) {
        console.error('Error adding mock data:', error);
    } finally {
        // Disconnect from MongoDB
        await mongoose.disconnect();
        console.log('Disconnected from MongoDB');
    }
}

// Run the script
addMockData();
